#!/bin/sh
#
# This is the xinitrc startup script for xmonad
#
# Ideally, general xinitrc stuff would go in ~/.xinitrc. But I want to make
# sure that everything is under source control, so I'm going to put the general
# stuff in here instead. If we have more than 1 window manager we use (which is
# unlikely), then we'll just have to duplicate it.
# 

# TODO: some commands we do in the foreground, whereas some others we do in the
# background. It's unclear how conscious we were about some of these choices,
# so maybe consider making more of them started in the background to help speed
# up the start?


# from xmonad begginger's guide, arch wiki for xinitrc, etc.
xrdb -merge .Xresources


# fix the keys (specifically Return)
xmodmap ${HOME}/.Xmodmap


# set root cursor
#  so we'lll have a sane cursor when hovering over no window in particular
# from arch wiki/xmonad documentation
#  http://www.haskell.org/haskellwiki/Xmonad/Frequently_asked_question#Setting_the_X_cursor
xsetroot -cursor_name left_ptr


# background image
# This doesn't seem to work for wmii if called before wmii is run
#  Probably b/c wmii is "overwriting" the background on its own
# Does work for xmonad however, and we're moving towards that anyways
feh --bg-fill ${HOME}/.wallpaper.png &

# start conky
#  we're starting conky from xmonad.hs so that it'll be restarted on every
#  mod-q. That way it won't interfere with xmobar.
#~/.conky/conky_start.sh &

# start xscreensaver
xscreensaver -no-splash &


# battery notifications
~/bin/battery_notify_daemon.py &



# start trayer
~/.xmonad/start_trayer.sh


# start ibus-daemon, for alternate language input
ibus-daemon &



# Start redshift
#  Send output to a file in /tmp for debugging after adding this line. We can
#  later remove the log file.
# 2015-05-10
redshift & > /tmp/redshift.log

# start xmonad
# Note for a long time (years) I've been starting xmonad without the exec.
# Started using the exec on 2018-09-21.
exec xmonad

